import { ItemI } from "./interfaces";
export const items: ItemI[] = [
  { name: "Adobe XD" },
  { name: "Angular" },
  { name: "Ant Design" },
  { name: "Apollo" },
  { name: "ASP.NET" },
  { name: "AWS" },
  { name: "Azure" },
  { name: "Babel" },
  { name: "Bootstrap" },
  { name: "C" },
  { name: "Cassandra" },
  { name: "Chakra UI" },
  { name: "CircleCI" },
  { name: "Cypress" },
  { name: "D3.js" },
  { name: "Dart" },
  { name: "Deno" },
  { name: "CSS" },
  { name: "Django" },
  { name: "Docker" },
  { name: "Elasticsearch" },
  { name: "Elm" },
  { name: "Erlang" },
  { name: "ESLint" },
  { name: "Express" },
  { name: "FastAPI" },
  { name: "Framer Motion" },
  { name: "Figma" },
  { name: "Firebase" },
  { name: "Flask" },
  { name: "Flutter" },
  { name: "Go" },
  { name: "Google Cloud" },
  { name: "GraphQL" },
  { name: "Haskell" },
  { name: "Heroku" },
  { name: "Ionic" },
  { name: "Java" },
  { name: "JavaScript" },
  { name: "Jenkins" },
  { name: "Jest" },
  { name: "jQuery" },
  { name: "Kotlin" },
  { name: "Kubernetes" },
  { name: "Laravel" },
  { name: "LESS" },
  { name: "Material UI" },
  { name: "Mocha" },
  { name: "MongoDB" },
  { name: "MySQL" },
  { name: "Next.js" },
  { name: "Nginx" },
  { name: "NoSQL" },
  { name: "Node.js" },
  { name: "Nuxt.js" },
  { name: "Oracle" },
  { name: "Pandas" },
  { name: "Perl" },
  { name: "PHP" },
  { name: "PostgreSQL" },
  { name: "Prettier" },
  { name: "Python" },
  { name: "PyTorch" },
  { name: "Rails" },
  { name: "React" },
  { name: "React Native" },
  { name: "Redis" },
  { name: "Redux" },
  { name: "Ruby" },
  { name: "Rust" },
  { name: "SASS" },
  { name: "SCSS" },
  { name: "Selenium" },
  { name: "Svelte" },
  { name: "SQL" },
  { name: "SQLite" },
  { name: "Spring Boot" },
  { name: "SQL Server" },
  { name: "Strapi" },
  { name: "Swift" },
  { name: "Tailwind CSS" },
  { name: "TensorFlow" },
  { name: "TypeScript" },
  { name: "Unity" },
  { name: "Vercel" },
  { name: "Vue.js" },
  { name: "Webpack" },
  { name: "Xamarin" },
];

export const len = ["Short", "Medium", "Long"];
export const diff = ["Beginner", "Intermediate", "Advanced"];
